-- ==========================================
-- Ferguson Auto Sales - Supabase Database Setup
-- Run this in your Supabase project's SQL Editor
-- ==========================================

-- 1. DROP EXISTING TABLES (If any exist to ensure clean setup)
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.cars CASCADE;

-- 2. CREATE INVENTORY CARS TABLE
CREATE TABLE public.cars (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    brand text NOT NULL,
    year integer NOT NULL,
    price numeric NOT NULL,
    mileage text,
    status text NOT NULL DEFAULT 'Available',
    category text,
    fuel text NOT NULL DEFAULT 'Petrol',
    color text,
    description text,
    power text,
    speed text,
    acceleration text,
    badge text DEFAULT 'New',
    badge_color text DEFAULT '#e50914',
    type text NOT NULL DEFAULT 'Sedan',
    image text NOT NULL DEFAULT '🚗',
    rating numeric DEFAULT 4.5,
    reviews integer DEFAULT 0,
    admin_added boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. CREATE CUSTOMER ORDERS TABLE
CREATE TABLE public.orders (
    id text PRIMARY KEY, -- Will hold the #BZ-XXXXXX formatted ID
    customer text NOT NULL,
    email text,
    phone text,
    car text NOT NULL,
    amount numeric NOT NULL,
    payment text NOT NULL DEFAULT 'WhatsApp Checkout',
    date text NOT NULL,
    status text NOT NULL DEFAULT 'Pending',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. CREATE CONTACT MESSAGES TABLE
CREATE TABLE public.messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text,
    phone text,
    subject text NOT NULL,
    message text NOT NULL,
    tag text NOT NULL DEFAULT 'General',
    read boolean DEFAULT false,
    replied boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. DISABLE ROW LEVEL SECURITY (RLS) FOR CONVENIENCE WITH CLIENT-SIDE CRUD
-- (Allows full access to anyone using the anon API key, matching the previous LocalStorage behavior but making it live)
ALTER TABLE public.cars DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;

-- 6. SEED CARS WITH PREMIUM INVENTORY (Beautiful Unsplash high-res vehicle imagery)
INSERT INTO public.cars 
    (name, brand, year, price, mileage, status, category, fuel, color, description, power, speed, acceleration, badge, badge_color, type, image, rating, reviews, admin_added) 
VALUES 
    (
        '2023 Lamborghini Aventador SVJ', 
        'Lamborghini', 
        2023, 
        395000, 
        '1,200 mi', 
        'Available', 
        'Supercar', 
        'Petrol', 
        'Mantis Green', 
        'The Aventador SVJ is the absolute pinnacle of naturally aspirated V12 performance, combining extreme aerodynamics with jaw-dropping exhaust notes.', 
        '770 HP', 
        '350 km/h', 
        '2.8s', 
        'Featured', 
        '#e50914', 
        'Supercar', 
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80', 
        4.9, 
        18, 
        true
    ),
    (
        '2024 Porsche 911 GT3 RS', 
        'Porsche', 
        2024, 
        245000, 
        '500 mi', 
        'Available', 
        'Sports Car', 
        'Petrol', 
        'Shark Blue', 
        'Motorsport DNA engineered for the streets. Features carbon fiber composite panels and an active rear wing producing 860kg of downforce.', 
        '518 HP', 
        '296 km/h', 
        '3.2s', 
        'New Arrival', 
        '#f5c518', 
        'Sports Car', 
        'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=800&q=80', 
        4.8, 
        12, 
        true
    ),
    (
        '2022 BMW M5 CS Limited', 
        'BMW', 
        2022, 
        140000, 
        '4,500 mi', 
        'Available', 
        'Luxury Sedan', 
        'Petrol', 
        'Frozen Deep Green', 
        'The quickest and most powerful road-legal BMW ever built. A true collector item combining V8 twin-turbo performance with lightweight carbon race buckets.', 
        '627 HP', 
        '305 km/h', 
        '3.0s', 
        'Limited', 
        '#00b894', 
        'Sedan', 
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80', 
        4.7, 
        9, 
        true
    ),
    (
        '2021 Mercedes-AMG GT Black Series', 
        'Mercedes', 
        2021, 
        320000, 
        '1,800 mi', 
        'Available', 
        'Supercar', 
        'Petrol', 
        'Magma Beam Orange', 
        'Direct track-to-road experience. A flat-plane twin-turbo V8, hand-adjustable carbon aero, and Nürburgring pedigree in an exclusive limited production run.', 
        '720 HP', 
        '325 km/h', 
        '3.2s', 
        'Exclusive', 
        '#1e50ff', 
        'Supercar', 
        'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=800&q=80', 
        4.9, 
        14, 
        true
    );
